<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Support\Str;

class PlanUser extends Model
{
    protected $table = "plan_user" ;

    protected $fillable = [
        "expire_at" ,
        "uid",
        "status" ,
        "user_id" ,
        "plan_id" ,
        "expire_at" ,
    ];


    protected $dates = [
        "expire_at"
    ] ;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        PlanUser::saving(function ($model){
            if ( is_null($model->uid) )
                $model->uid = Str::random(30) ;
        }) ;

    }

    public function user()
    {
        return $this->belongsTo(User::class ) ;
    }

    public function plan()
    {
        return $this->belongsTo( Plan::class ) ;
    }

    public function teams()
    {
        return $this->hasMany( Team::class ) ;
    }

}
